### ISSUE TITLE
Add log level to the console printouts

### ISSUE THREAD

**Issue by zlanaz** [ALERTua/global_logger#1]
* Global Logger version: 0.3.16
* Python version: 3.9
* Operating System: Windows 10

### Add log level to the console printouts

Currently the console logs come without the the log level
Improvement: Add log level to the console printouts

### My solution (I can do it but I think someone that already has the solution set up could do this much faster...):
In  the global_logger.py
Update:
LOGGER_COLORED_MESSAGE_FORMAT = '%(log_color)s%(message)s'
to
LOGGER_COLORED_MESSAGE_FORMAT = '%(levelname)s: %(log_color)s%(message)s'

or ask user to pass a parameter that would allow them to customize the console logs as they wish or when setting the message_format apply that to the console log as well, similar to how we already do  for the designated file logging. 

logger_message_format = '%(asctime)s: %(filename)s:%(funcName)s: %(levelname)s: %(message)s'
log = Log.get_logger(message_format=logger_message_format)

Additionally, allow user to turn off console logging

Cheers!
Lily

**Comment by ALERTua** [comment]
done in 0.3.17:

- added Python 3.9 support
- renamed message_format argument to file_message_format
- added screen_message_format argument that you can use to override the default screen logging message format.

to disable screen logging, you can raise the global logging level to something like 999, and no log message level will be equal or higher than this number so the output should be empty. in this case, only file output will exist if enabled.

are you satisfied with these changes? can I do anything else for you?

**Comment by zlanaz** [comment]
Alexey Thank You Furrry Much (Paws up)

**Comment by ALERTua** [comment]
Please do not hesitate to leave a comment if something isn't working as expected or needs enhancement.
For now, I am closing this issue.
